### ISSUE TITLE
API changes?

### ISSUE THREAD

**Issue by JulienPalard** [turtl/core-rs#1]
Hi Andrew,

I appreciate the work you're doing with turtl, I use it daily since like a year, so first: thanks.

I needed an offline backup tool, as I'm not hosting my own turtl server but using framanotes.org, so I did it: https://github.com/JulienPalard/turtl-backup (bare minimum, just auth, sync all, save to file, done).

I just wanted to know if you're currently changing the API with core-rs / new backend in node.js or if the current API will be stable?

**Comment by orthecreedence** [comment]
Hi, Julien. Sorry for the lag, this slipped through the cracks in my email.

The APIs are changing. Right now, we use AES-GCM, this will switch to chacha20-poly1305, specifically what's used in [libsodium](https://github.com/jedisct1/libsodium), however the serialization format for encrypted data will stay very similar to what it is now. There are a few other changes as well, such as a new type called `spaces` that contains boards/notes, but if you're just grabbing notes and decrypting them you shouldn't have to care too much about that.

I'm guessing you should be able to keep a lot of the work you've done already, and swap out the crypto to use libsodium. Sorry for the extra work, hope this overview helps a bit (and sorry if I'm forgetting something, I've been working on the new version for a while now and the differences from the old version aren't fresh in my brain anymore).
