### ISSUE TITLE
Crypto error on another device after changing the password

### ISSUE THREAD

**Issue by jxcr0w** [turtl/core-rs#2]
I am using Turtl with mobile and Desktop. Whenever I change my password using either of them, decrypting the notes fails in the other (see the attached picture). 

That is, I changed my password in the android app, and got 'Crypto error's in the Desktop app. When I changed my password back to what it was, the app was able to decrypt the notes again.

![turtl](https://user-images.githubusercontent.com/14980771/35436817-2da08436-0290-11e8-90c0-69161ad8a412.png)

**Comment by jxcr0w** [comment]
Apparently, 
Doing 
Your Settings -> Clear Local Data
Solves Crypto errors. 

Nevertheless, this issue should be fixed.

Cheers,
jxcr0w

**Comment by orthecreedence** [comment]
This issue is the bane of my existence. I've been testing the upcoming v0.7
release quite a lot and so far no crypto errors. It also ships with a full
suite of tests that make sure everything is functioning as expected. Long
overdue. Thanks for the report.
